---

- hosts: all
  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: pulp-fips
      when:
        - enable_fips is defined
        - enable_fips
    - role: os-update

