---

- hosts: all
  pre_tasks:
    - name: Check fips state
      shell: cat /proc/sys/crypto/fips_enabled
      register: fips_state
  vars:
    repo_priority: "{{ '50' if fips_state.stdout == '1'  else '99' }}"

  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: pulp-fips
      when:
        - enable_fips is defined
        - enable_fips
    - role: pulp
    - role: lazy
      when: pulp_version is version('2.8', '>=')
    - role: pulp-certs
    - role: pulp-crane
